(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};shapesData={"shape1":[[],[],[],[36,0,105],[23,0,70]],"shape2":[[],[],[],[231,0,125,230,0,3,229,0,2,228,0,1,227,0,2,226,0,1,225,0,1,224,0,1,223,0,1,221,0,1,220,0,1,218,0,1,215,0,1,1,0,1,0,0,161],[153,0,84,152,0,2,151,0,1,150,0,2,149,0,1,147,0,1,146,0,1,144,0,1,1,0,1,0,0,108]]};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/foto-976.jpg':'images/foto-488.jpg');
var a='data-src';var e=document.querySelector('.js6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra-826.jpg':'images/chitarra-413.jpg');
var a='data-src';var e=document.querySelector('.js7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/furgone-200.png':'images/furgone-100.png');
var a='data-src';var e=document.querySelector('.js8 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/none-1200.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/none-1200-1.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/none-1200-2.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/none-1200-3.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/734488-2400.jpg':'images/734488-1200.jpg');
var a='data-src';var e=document.querySelector('.js9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live4-750.jpg':'images/live4-375.jpg');
var a='data-src';var e=document.querySelector('.js10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra2-750.jpg':'images/chitarra2-375.jpg');
var a='data-src';var e=document.querySelector('.js11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live3-750.jpg':'images/live3-375.jpg');
var a='data-src';var e=document.querySelector('.js12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/facebook-100.png');
var a='data-src';var e=document.querySelector('.js13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/twitter-100.png');
var a='data-src';var e=document.querySelector('.js14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/instagram-100.png');
var a='data-src';var e=document.querySelector('.js15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/youtube-100.png');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/foto3-876.jpg':'images/foto3-438.jpg');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/video-600.png':'images/video-300.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?'images/video-600.png':'images/video-300.png');
var e=document.querySelector('.js5');e.setAttribute('src',(dpi>1)?'images/video-600.png':'images/video-300.png');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/foto-780.jpg':'images/foto-390.jpg');
var a='data-src';var e=document.querySelector('.js6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra-660.jpg':'images/chitarra-330.jpg');
var a='data-src';var e=document.querySelector('.js7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/furgone-160.png':'images/furgone-80.png');
var a='data-src';var e=document.querySelector('.js8 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/none-960-1.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1920.jpg':'images/none-960-3.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/none-960-5.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/none-960-7.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/734488-1920.jpg':'images/734488-960-1.jpg');
var a='data-src';var e=document.querySelector('.js9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live4-600.jpg':'images/live4-300.jpg');
var a='data-src';var e=document.querySelector('.js10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra2-600.jpg':'images/chitarra2-300.jpg');
var a='data-src';var e=document.querySelector('.js11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live3-600.jpg':'images/live3-300.jpg');
var a='data-src';var e=document.querySelector('.js12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/facebook-80.png');
var a='data-src';var e=document.querySelector('.js13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/twitter-80.png');
var a='data-src';var e=document.querySelector('.js14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/instagram-80.png');
var a='data-src';var e=document.querySelector('.js15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/youtube-80.png');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/foto3-700.jpg':'images/foto3-350.jpg');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/video-480.png':'images/video-240-1.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?'images/video-480.png':'images/video-240-1.png');
var e=document.querySelector('.js5');e.setAttribute('src',(dpi>1)?'images/video-480.png':'images/video-240-1.png');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/foto-624.jpg':'images/foto-312.jpg');
var a='data-src';var e=document.querySelector('.js6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra-528.jpg':'images/chitarra-264.jpg');
var a='data-src';var e=document.querySelector('.js7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/furgone-128.png':'images/furgone-64.png');
var a='data-src';var e=document.querySelector('.js8 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536.jpg':'images/none-768.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536-1.jpg':'images/none-768-1.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536-2.jpg':'images/none-768-2.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536-3.jpg':'images/none-768-3.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/734488-1536.jpg':'images/734488-768.jpg');
var a='data-src';var e=document.querySelector('.js9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live4-480-1.jpg':'images/live4-240.jpg');
var a='data-src';var e=document.querySelector('.js10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra2-480-1.jpg':'images/chitarra2-240.jpg');
var a='data-src';var e=document.querySelector('.js11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live3-480.jpg':'images/live3-240.jpg');
var a='data-src';var e=document.querySelector('.js12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/facebook-64.png');
var a='data-src';var e=document.querySelector('.js13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/twitter-64.png');
var a='data-src';var e=document.querySelector('.js14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/instagram-64.png');
var a='data-src';var e=document.querySelector('.js15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/youtube-64.png');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/foto3-560.jpg':'images/foto3-280.jpg');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/video-384.png':'images/video-192.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?'images/video-384.png':'images/video-192.png');
var e=document.querySelector('.js5');e.setAttribute('src',(dpi>1)?'images/video-384.png':'images/video-192.png');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/foto-960.jpg':'images/foto-480.jpg');
var a='data-src';var e=document.querySelector('.js6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra-620.jpg':'images/chitarra-310.jpg');
var a='data-src';var e=document.querySelector('.js7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/furgone-230.png':'images/furgone-115.png');
var a='data-src';var e=document.querySelector('.js8 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960.jpg':'images/none-480.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960-2.jpg':'images/none-480-1.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960-4.jpg':'images/none-480-2.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960-6.jpg':'images/none-480-3.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/734488-960.jpg':'images/734488-480.jpg');
var a='data-src';var e=document.querySelector('.js9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live4-960.jpg':'images/live4-480.jpg');
var a='data-src';var e=document.querySelector('.js10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra2-960.jpg':'images/chitarra2-480.jpg');
var a='data-src';var e=document.querySelector('.js11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live3-958.jpg':'images/live3-479.jpg');
var a='data-src';var e=document.querySelector('.js12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/facebook-90.png');
var a='data-src';var e=document.querySelector('.js13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/twitter-91.png');
var a='data-src';var e=document.querySelector('.js14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/instagram-91.png');
var a='data-src';var e=document.querySelector('.js15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/youtube-90.png');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/foto3-418.jpg':'images/foto3-209.jpg');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/video-240.png':'images/video-120.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?'images/video-240.png':'images/video-120.png');
var e=document.querySelector('.js5');e.setAttribute('src',(dpi>1)?'images/video-240.png':'images/video-120.png');}else{var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/foto-640.jpg':'images/foto-320.jpg');
var a='data-src';var e=document.querySelector('.js6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra-414.jpg':'images/chitarra-207.jpg');
var a='data-src';var e=document.querySelector('.js7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/furgone-154.png':'images/furgone-77.png');
var a='data-src';var e=document.querySelector('.js8 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640.jpg':'images/none-320.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640-1.jpg':'images/none-320-1.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640-2.jpg':'images/none-320-2.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640-3.jpg':'images/none-320-3.jpg');
var a='data-src';var e=document.querySelector('.js8 .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/734488-640.jpg':'images/734488-320.jpg');
var a='data-src';var e=document.querySelector('.js9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live4-640.jpg':'images/live4-320.jpg');
var a='data-src';var e=document.querySelector('.js10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/chitarra2-640.jpg':'images/chitarra2-320.jpg');
var a='data-src';var e=document.querySelector('.js11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/live3-638.jpg':'images/live3-319.jpg');
var a='data-src';var e=document.querySelector('.js12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/facebook-120.png':'images/facebook-60.png');
var a='data-src';var e=document.querySelector('.js13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/twitter-122.png':'images/twitter-61.png');
var a='data-src';var e=document.querySelector('.js14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/instagram-122.png':'images/instagram-61.png');
var a='data-src';var e=document.querySelector('.js15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/youtube-120.png':'images/youtube-60.png');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/foto3-278.jpg':'images/foto3-139.jpg');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/video-160.png':'images/video-80.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?'images/video-160.png':'images/video-80.png');
var e=document.querySelector('.js5');e.setAttribute('src',(dpi>1)?'images/video-160.png':'images/video-80.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
ldsrcset('.js76 source');ldsrcset('.js77 source');ldsrcset('.js78 source');$('.js8 .slider').slick({lazyLoad: 'ondemand',slidesToShow: 1,slidesToScroll: 1,overflow: 'hidden',fade: true,slide: 'div',cssEase: 'linear',speed: 100,dots: true,arrows: false,infinite: true,autoplay: true,pauseOnHover: false,autoplaySpeed: 2500});ldsrcset('.js79 source');ldsrcset('.js80 source');ldsrcset('.js81 source');ldsrcset('.js82 source');ldsrcset('.js83 source');ldsrcset('.js84 source');ldsrcset('.js85 source');var s=new Shapes();window.onresize=function(){s.update();};s.update();if(location.hash){var o=location.hash.replace('#',''),e=function(){if(document.body.getBoundingClientRect().top>0){var t=document.querySelectorAll('[name="'+o+'"]')[0];t&&t.scrollIntoView(!0),setTimeout(e,100)}};e()}
});